---
- hosts: web
  tasks:
    - name: creating FILE
      file:
        name: /home/ubuntu/test
        state: touch
    - name: create directory
      file:
        name: /home/ubuntu/testdir      
        mode: 0777
        state: directory 
